package org.ecommerce.project.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "payment")
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId;
    // This payment id is generated by our application

    @OneToOne(mappedBy = "payment")
    private Order order;
    // One order will have one payment done to it
    // NOTE : mappedBy is used to show the inverse side of the relation, so Payment field in the Order is the OWNER of this relation (imp)


    @NotBlank
    @Size(min = 3, message = "Payment method must contain atleast 4 characters")
    private String paymentMethod;

    // Below payment Id will be generated by the payment gateway
    // pg -> paymentGateway
    private String pgPaymentId;
    private String pgStatus;
    private String pgResponseMessage;
    private String pgName;

    // We will be creating the payment object without having the order information, therefore we created this custom constructor
    public Payment(Long paymentId, String pgPaymentId, String pgStatus, String pgResponseMessage, String pgName){
        this.paymentId = paymentId;
        this.pgPaymentId = pgPaymentId;
        this.pgStatus = pgStatus;
        this.pgResponseMessage = pgResponseMessage;
        this.pgName = pgName;
    }
}
